subroutine ranseq(k,lu)

! (copied from Kiran's CUDA code)
!
!  purpose:
!       this routine permits different random numbers sequences within
!       the same program.  each sequence is designated a k-number.
!       ( k is the first argument to ranseq.  1 .le. k .le. nk=20 .)
!       random numbers from the sequence can be generated by ranu2,
!       or by any routine calling ranu2, or by any routine using the
!       seed  iseed  in common block  rancom.
!  use:
!       call ranseq(k) causes random numbers to be generated from sequen
!       this sequence will be used until the next call.
!
!       the argument lu is relevant only if k is -1 or -2 (see below)
!
!  initialization:
!       by default, all k seeds are initially set to the same value.
!       ranseq must be called to set initial k value before any other
!       random number routines are called.
!       if ranseq is called with the argument k= -1, then the seeds are
!       read (formatted) from logical unit lu.
!       alternatively, seeds can be specified by calling seqput.
!
!  checkpointing:
!       if ranseq is called with the argument k= -2, then the seeds are
!       written (formatted) on logical unit lu.
!       alternatively, seeds can be obtained by calling seqget.
!
!-----------------------------------------------------------------------
 
   use mpicom
   use com, only: seed_input
 
   use ranseed
   implicit none
 
   integer iseq,nk,klast
   parameter ( nk=20 )
   common/seqcom/iseq(nk),klast
   integer iseqdf(nk)
   integer seed,ifst,k,lu,i,iset
 
   integer no_err,no_end
 
   data ifst/0/
   data iseqdf/ nk* 0 /
    
   !!!first call only
   
   !if (taskid.eq.0) write(6,*)'enter ranseq: ifst,k=',ifst,k

   if ( ifst .eq. 0 ) then
      ifst = 1

      if (taskid.eq.0) then
         write (6,*) 'taskid,1st call of ranseq: k,lu=',taskid,k,lu
         write (6,*) 'ranseq: taskid,seed_input=',taskid,seed_input
      end if

      !if (iseqdf(1).eq.0.and.k.ne.-1) then
      !write (6,*) 'specify default random no. seed'
      !read (5,*) seed

      if (iseqdf(1).eq.0.and.k.ne.-1) then
         seed=seed_input
         do i=1,nk
            iseqdf(i)=seed
         end do
         if (taskid.eq.0) write (6,*) 'ranseq: taskid,seed from stdin:',taskid,seed
      end if
 
      !  initial value of seeds
 
      if( k .eq. -1 ) then
 
         no_err=0
         if (taskid.eq.0) then
            read (lu,100,err=15,end=15) iseq
         end if
         go to 16
 15      no_err=1
 16      continue
         call MPI_BCAST (no_err,1,MPI_INTEGER,0,MPI_COMM_WORLD,mpierr)
         if (no_err.gt.0) then
            if (taskid.eq.0) write (6,*) &
                'Code stops because of error in reading ''ranin'' file'
            stop
         end if

         call MPI_BCAST (iseq,nk,MPI_INTEGER,0,MPI_COMM_WORLD,mpierr)
 
      else
 
         !  have they been set in seqput ?  if not, use default values.
 
         call seqset(1,iset)
         if( iset .eq. 0 ) then
            do i=1,nk
               iseq(i) = iseqdf(i)
            end do
         endif

      endif
 
      klast = 1
      iseed = iseq(1)
      if( k .eq. -1 ) return
 
   endif
 
   ! general call
 
   if( k .gt. nk ) then
      write(6,*)' k=',k,' must be less than nk=',nk
      write(6,*)' parameter nk can be increased in ranseq '
      write(6,*)' stopped in ranseq '
      stop
   else if( k .gt. 0 ) then
      iseq(klast) = iseed
      klast = k
      iseed = iseq(klast)
      continue
   else if( k .eq. -1 ) then
      read(lu,100)iseq
   else if( k .eq. -4 ) then
      !! nothing here
   else if( k .eq. -2 ) then
      iseq(klast) = iseed
      !rewind lu
      !call fclose1 (lu)
      !call fopen1 (lu,'ranout ','formatted  ')
      !write(lu,100)iseq
      !call fclose1 (lu)
      if (taskid.eq.0) write(lu,100)iseq
   else
      write(6,*)' invalid argument: k=',k
      write(6,*)' stopped in ranseq '
      stop
   endif
   return
 
100     format( (5i15) )
 
end


!!! ----------------------------


subroutine seqput(n,iseqpt)
 
   !  routine to set seeds
   !  arguments:
   !       n      - number of seeds
   !       iseqpt - seeds
 
   parameter (nk=20)
   common/seqcom/iseq(nk),klast
   dimension iseqpt(n)
   save ifst
   data ifst/0/
 
   if( n .gt. nk ) then
      write(6,*)' nk=',nk,' must be .ge. n=',n
      write(6,*)' stopped in seqput '
      stop
   else if( n .gt. nk ) then
      write(6,*)' only ',n,' out of ',nk,' seeds set in seqput '
   endif
 
   ifst = 1
   do 10 i=1,n
      if( iseqpt(i) .gt. 0 ) then
         iseq(i) = iseqpt(i)
      else
         write(6,*)' invalid seed iseqpt(',i,') =',iseqpt(i)
         write(6,*)' stopped in seqput '
         stop
      endif
10 continue
 
   return

   !! code returns before completing the following
   entry seqset(n,iset)
   iset = ifst

   return
end
